/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.stjohnwheaton.sociallydistantgroupedseatingwrapper;

import java.awt.Dimension;

/**
 *
 * @author emili
 */
public class MessageDisplay extends javax.swing.JDialog
{

    /**
     * Creates new form MessageDisplay
     */
    public MessageDisplay(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    public void setText(String titleText, String messageText, String buttonText, String txtAreaText)
    {
        this.setTitle(titleText);
        lblTitle.setText(messageText);
        btnOK.setText(buttonText);
        if (txtAreaText != null && txtAreaText.length() > 0)
        {
            txtAreaMoreInfo.setText(txtAreaText);
            scrollMoreInfo.setBounds(scrollMoreInfo.getX(), scrollMoreInfo.getY(), 200, 200);
            scrollMoreInfo.setPreferredSize(new Dimension(200, 200));
            txtAreaMoreInfo.setBounds(txtAreaMoreInfo.getX(), txtAreaMoreInfo.getY(), 200, 200);    
            txtAreaMoreInfo.setPreferredSize(new Dimension(200, 200));
            scrollMoreInfo.invalidate();
            txtAreaMoreInfo.invalidate();
            this.setSize(this.getWidth(), this.getHeight() + 250);
            //this.invalidate();
            this.doLayout();
            this.pack();
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblTitle = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        scrollMoreInfo = new javax.swing.JScrollPane();
        txtAreaMoreInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTitle.setText("Title");

        btnOK.setText("OK");
        btnOK.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btnOKMouseClicked(evt);
            }
        });

        scrollMoreInfo.setMinimumSize(new java.awt.Dimension(0, 0));
        scrollMoreInfo.setPreferredSize(new java.awt.Dimension(200, 5));
        scrollMoreInfo.setViewportView(txtAreaMoreInfo);

        txtAreaMoreInfo.setEditable(false);
        txtAreaMoreInfo.setBackground(javax.swing.UIManager.getDefaults().getColor("TextPane.disabledBackground"));
        txtAreaMoreInfo.setColumns(20);
        txtAreaMoreInfo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtAreaMoreInfo.setEnabled(false);
        txtAreaMoreInfo.setMinimumSize(new java.awt.Dimension(200, 0));
        txtAreaMoreInfo.setPreferredSize(new java.awt.Dimension(200, 10));
        txtAreaMoreInfo.setRequestFocusEnabled(false);
        txtAreaMoreInfo.setSelectionColor(new java.awt.Color(0, 0, 153));
        txtAreaMoreInfo.setVerifyInputWhenFocusTarget(false);
        scrollMoreInfo.setViewportView(txtAreaMoreInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollMoreInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOK)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOK)
                .addGap(18, 18, 18)
                .addComponent(scrollMoreInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btnOKMouseClicked
    {//GEN-HEADEREND:event_btnOKMouseClicked
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnOKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MessageDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MessageDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MessageDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MessageDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                MessageDisplay dialog = new MessageDisplay(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane scrollMoreInfo;
    private javax.swing.JTextArea txtAreaMoreInfo;
    // End of variables declaration//GEN-END:variables
}
